apiVersion: v1
kind: Pod
metadata:
  name: guestbook-ui-test
  labels:
    app: guestbook-ui
spec:
  containers:
  - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
    name: guestbook-ui
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 32Mi
